    program main
    
    use mpi
    use decomp_2d
    use readWriteHDF5
    use timeIntegration
    use nseq
    use derivs
    use iso_c_binding
    
    implicit none

    interface
        function get_cpu_time() bind(C)
            import :: c_double
            real(c_double) :: get_cpu_time
        end function
    end interface
    
    ! Read parameters file generated by Matlab
    include 'parameters.F90'
    
    ! Declare variables for the matrices
    integer :: nDerivBlocksX, nDerivBlocksY, nDerivBlocksZ
    integer, dimension(:,:), allocatable :: derivBlocksX, derivBlocksY, derivBlocksZ
    integer :: derivnRHSx, filternRHSx, derivnRHSy, filternRHSy, derivnRHSz, filternRHSz
    
    real*8, dimension(:,:),   allocatable :: derivsAX, derivsBX, derivsCX, filterAX, filterBX, filterCX
    real*8, dimension(:,:,:), allocatable :: derivsRX, filterRX
    
    real*8, dimension(:,:),   allocatable :: derivsAY, derivsBY, derivsCY, filterAY, filterBY, filterCY
    real*8, dimension(:,:,:), allocatable :: derivsRY, filterRY
    
    real*8, dimension(:,:),   allocatable :: derivsAZ, derivsBZ, derivsCZ, filterAZ, filterBZ, filterCZ
    real*8, dimension(:,:,:), allocatable :: derivsRZ, filterRZ
    
    real*8 ,dimension(:,:),   allocatable :: derivsDX, derivsDY, derivsDZ, filterDX, filterDY, filterDZ
    integer :: periodicX, periodicY, periodicZ, filterX, filterY, filterZ
    
    integer :: neumannLength, neumann2Length
    real*8, dimension(:), allocatable :: neumannCoeffs, neumann2Coeffs
    
    ! Declare variables for the boundaries
    integer :: nUd, nVd, nWd, nPd, nEd, nUn, nVn, nWn, nPn, nEn, nUs, nVs, nWs, nPs, nEs ! Number of each type of boundary
    integer, dimension(:,:), allocatable :: iUd, iVd, iWd, iPd, iEd, iUn, iVn, iWn, iPn, iEn, iUs, iVs, iWs, iPs, iEs ! Index for each boundary
    real*8,  dimension(:),   allocatable :: vUd, vVd, vWd, vPd, vEd ! Value for Dirichlet conditions
    integer, dimension(:),   allocatable :: dUn, dVn, dWn, dPn, dEn ! Direction for Neumann conditions
    integer, dimension(:),   allocatable :: dUs, dVs, dWs, dPs, dEs ! Direction for null second derivative conditions
    
    integer :: cN ! Number of corners
    integer, dimension(:,:), allocatable :: cL, cD ! Location and direction for corners
    integer, dimension(:), allocatable :: cAdiabatic ! Adiabatic flag for corners
    
    ! Declare flow variables
    real*8,  dimension(:,:,:), allocatable :: SFD_X
    real*8,  dimension(:,:,:), allocatable :: U,V,W,R,E
    logical, dimension(:,:,:), allocatable :: insideWall
    real*8,  dimension(:,:,:), allocatable :: Umean,Vmean,Wmean,Rmean,Emean
    real*8,  dimension(:,:,:), allocatable :: Unew,Vnew,Wnew,Rnew,Enew
    real*8,  dimension(5)                  :: maxChange, maxChangeL, minChange

    ! Declare domain decomposition variables
    integer :: ierror
    integer, dimension(:), allocatable :: sliceSizes, slicesJStarts, slicesJEnds, slicesKStarts, slicesKEnds
    
    ! Declare time stepping variables
    real*8 :: t, dt
    integer :: nTracked
    real*8, dimension(5) :: trackedValues
    integer, dimension(:,:), allocatable :: indTracked
    real*8 :: CFLdt, CFL, UmaxL, VmaxL, WmaxL, Umax, Vmax, Wmax
    integer :: tstep, nSaveTemp, simulationDone, stepsUntilSaving
    
    ! Declare rest of the variables
    real*8 :: NaN
    integer :: i,j,k
	logical :: stopDNS = .FALSE.

    ! Variables for collectiveImportFlow.F90    
    integer :: domain_dims(5)
    integer, allocatable :: dimensions(:), sendcounts(:), displs(:)

    ! Variables for writeTrackedPoints2.F90    
    real(8), allocatable :: local_values(:,:), global_values(:,:,:)

    ! Variables for writeTrackedPoints3.F90    
    integer :: tp_packed_size, tmp_pack_size, tp_position, tp_total_size
    integer, allocatable :: tp_sendcounts(:), tp_displs(:)
    character(len=:), allocatable :: tp_sendbuf, tp_recvbuf

    ! Variables for time instrumentation
    real*8 :: t1, t2, t3
    integer :: dt_values(8)
    real*8 :: total_time, cpu_time, comm_time, io_time, imp_time, exp_time, track_time
    real*8 :: max_comm_time, min_comm_time, sum_comm_time, max_io_time, min_io_time, sum_io_time
    real*8 :: max_total_time, min_total_time, sum_total_time, max_cpu_time, min_cpu_time, sum_cpu_time
    real(c_double) :: tc1, cpu_usage_time, max_cpu_usage_time, min_cpu_usage_time, sum_cpu_usage_time 
    real*8 :: max_imp_time, min_imp_time, sum_imp_time, max_exp_time, min_exp_time, sum_exp_time, max_track_time, min_track_time, sum_track_time

    ! INITIALIZE DOMAIN DECOMPOZITION
    call mpi_init(ierror)
    call decomp_2d_init(nx,ny,nz,p_row,p_col)
    ! print *, 'Rank', nrank, ' decomp_2d_init [nx, ny, nz]: ', [nx, ny, nz]
    
    ! Read matrices and boundaries files generated by Matlab
    include 'matrices.F90'
    include 'boundaryInfo.F90'
    
    ! IMPORT FLOW
    allocate(U(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
    allocate(V(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
    allocate(W(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
    allocate(R(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
    allocate(E(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
    allocate(insideWall(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
    
    U = 0; V = 0; W = 0; R = 0; E = 0
    cpu_time = 0.0d0; comm_time = 0.0d0; io_time = 0.0d0; exp_time = 0.0d0; track_time = 0.0d0
    
    !include 'importFlow2.F90'
    
    t1 = MPI_Wtime(); t2 = MPI_Wtime()
    ! Collective import via mpi/hdf5 asynchronous I/O
    call readFlow(nSave,t,U,V,W,R,E, insideWall, nx, ny, nz, NaN)
    io_time = io_time + (MPI_Wtime() - t2)

    ! APPLY BOUNDARIES
    call applyBoundCond(U,V,W,R,E,gamma,t, &
                & neumannLength, neumann2Length, neumannCoeffs, neumann2Coeffs, &
                & nUd, nVd, nWd, nPd, nEd, nUn, nVn, nWn, nPn, nEn, nUs, nVs, nWs, nPs, nEs, &
                & iUd, iVd, iWd, iPd, iEd, iUn, iVn, iWn, iPn, iEn, iUs, iVs, iWs, iPs, iEs, &
                & vUd, vVd, vWd, vPd, vEd, dUn, dVn, dWn, dPn, dEn, dUs, dVs, dWs, dPs, dEs, &
                & cN, cL, cD, cAdiabatic)
                
    ! INITIALIZE SFD
    if(SFD.gt.0) then ! If SFD changes along the domain, it is to be imported from a .mat
    
        allocate(sfd_X(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
        
        select case(SFD)
        case(1)
            sfd_X = sfd_X_val
        case(2)
            t2 = MPI_Wtime()
            ! Collective import via mpi/hdf5 asynchronous I/O
            call readSFD(sfd_X, nx, ny, nz)
            io_time = io_time + (MPI_Wtime() - t2)
        end select
    endif
    
    if(SFD.gt.0) then
    
        allocate(Umean(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
        allocate(Vmean(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
        allocate(Wmean(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
        allocate(Rmean(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
        allocate(Emean(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
    
		if(resumeMeanFlow.eq.1) then
			!include 'importMeanFlow.F90'
        
            t2 = MPI_Wtime()
            ! Collective import via mpi/hdf5 asynchronous I/O
            call readMeanFlow(Umean,Vmean,Wmean,Rmean,Emean, insideWall, nx, ny, nz, NaN)
            io_time = io_time + (MPI_Wtime() - t2)
		else
			Umean = U; Wmean = W; Rmean = R; Emean = E
		endif
    endif
    imp_time = MPI_Wtime() - t1

    ! RUN TIME STEPPING
    simulationDone = 0
	
	select case (timeControl)
		case(1) !Continue the iteration count if the dt is fixed
			tstep = nSave
		case(2) !Reset the count if the dt is variable
			tstep = 0
	end select
    
    ! Allocate variables for next step
    allocate(Unew(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
    allocate(Vnew(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
    allocate(Wnew(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
    allocate(Rnew(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
    allocate(Enew(xstart(1):xend(1), xstart(2):xend(2), xstart(3):xend(3)))
    
    ! Allocate variables for 'writeTrackedPoints2.F90'
    allocate(local_values(5, nTracked), global_values(5, nTracked, nproc))

    stepsUntilSaving = 0
    Unew = 0; Vnew = 0; Wnew = 0; Rnew = 0; Enew = 0
    
    tc1 = get_cpu_time()
    total_time = MPI_Wtime()

    do while (simulationDone.eq.0)
    
        ! TIME CONTROL
        
        ! For fixed dt, evaluating CFL only once for while to optmize multi-node simulations...		
        if ((mod(tstep,logAll).eq.0).or.(stepsUntilSaving.eq.0).or.(timeControl.eq.2)) then

            ! Get maximum velocity from all slices
            UmaxL = maxval(abs(U))
            VmaxL = maxval(abs(V))

            t1 = MPI_Wtime()
            call MPI_Barrier(MPI_COMM_WORLD, ierror)
            
            call MPI_ALLREDUCE(UmaxL, Umax, 1, MPI_REAL8, MPI_MAX, MPI_COMM_WORLD, ierror)
            call MPI_ALLREDUCE(VmaxL, Vmax, 1, MPI_REAL8, MPI_MAX, MPI_COMM_WORLD, ierror)

            if (nz.gt.1) then ! For 3D
                WmaxL = maxval(abs(W))
                call MPI_ALLREDUCE(WmaxL, Wmax, 1, MPI_REAL8, MPI_MAX, MPI_COMM_WORLD, ierror)
            endif
            comm_time = comm_time + (MPI_Wtime() - t1)
        else
            Umax = maxval(abs(U))
            Vmax = maxval(abs(V))
        endif
        
        ! CFLdt is the CFL divided by dt
        if (nz.gt.1) then ! For 3D
            CFLdt = (1/Ma + Umax)*dxmin(1) + (1/Ma + Vmax)*dxmin(2) + (1/Ma + Wmax)*dxmin(3)
        else ! For 2D
            CFLdt = (1/Ma + Umax)*dxmin(1) + (1/Ma + Vmax)*dxmin(2)
        endif
        
        ! Determine time step and check for saving and ending
        select case (timeControl)
            case (1) ! Fixed dt
                if (mod(tstep + 1,qtimesInt).eq.0) then
                    stepsUntilSaving = 0
                    nSave = tstep + 1
                else
                    stepsUntilSaving = 1
                endif
                dt = dtmax
                
                if ((tstep+1).ge.tmaxInt) then
                    simulationDone = 1
                endif
                
            case (2) ! Maximum CFL
            
                if(stepsUntilSaving.eq.0) then
                    dt = min(maxCFL/CFLdt,dtmax)
                    stepsUntilSaving = floor(qtimesReal/dt)+1
                    dt = qtimesReal/stepsUntilSaving
                    nSave = nSave + 1
                endif
                
                stepsUntilSaving = stepsUntilSaving-1
                
                if ((t+dt).ge.tmaxReal) then
                    simulationDone = 1
                endif

            case (3) ! Hybrid: Maximum CFL followed by fixed dt.

                ! TODO

        end select
        
        CFL = dt*CFLdt
        
        t1 = MPI_Wtime()
        ! Call stepping routine
        if (nz.eq.1) then
            select case(timeStepping)
                case (1) ! RK4
                    call RK4_2D(U,V,W,R,E,Unew,Vnew,Rnew,Enew, &
                            & t, dt, Re, Ma, Pr, gamma, T0, &
                            & nDerivBlocksX,nDerivBlocksY,derivBlocksX,derivBlocksY, &
                            & derivnRHSx,derivnRHSy, &
                            & derivsAX, derivsBX, derivsCX, derivsRX, &
                            & derivsAY, derivsBY, derivsCY, derivsRY, &
                            & derivsDX, derivsDY, &
                            & periodicX, periodicY, &
                            & neumannLength, neumann2Length, neumannCoeffs, neumann2Coeffs, &
                            & nUd, nVd, nWd, nPd, nEd, nUn, nVn, nWn, nPn, nEn, nUs, nVs, nWs, nPs, nEs, &
                            & iUd, iVd, iWd, iPd, iEd, iUn, iVn, iWn, iPn, iEn, iUs, iVs, iWs, iPs, iEs, &
                            & vUd, vVd, vWd, vPd, vEd, dUn, dVn, dWn, dPn, dEn, dUs, dVs, dWs, dPs, dEs, &
                            & cN, cL, cD, cAdiabatic)
                            
                case (2) ! EULER
                    call EULER_2D(U,V,W,R,E,Unew,Vnew,Rnew,Enew, &
                            & t, dt, Re, Ma, Pr, gamma, T0, &
                            & nDerivBlocksX,nDerivBlocksY,derivBlocksX,derivBlocksY, &
                            & derivnRHSx,derivnRHSy, &
                            & derivsAX, derivsBX, derivsCX, derivsRX, &
                            & derivsAY, derivsBY, derivsCY, derivsRY, &
                            & derivsDX, derivsDY, &
                            & periodicX, periodicY, &
                            & neumannLength, neumann2Length, neumannCoeffs, neumann2Coeffs, &
                            & nUd, nVd, nWd, nPd, nEd, nUn, nVn, nWn, nPn, nEn, nUs, nVs, nWs, nPs, nEs, &
                            & iUd, iVd, iWd, iPd, iEd, iUn, iVn, iWn, iPn, iEn, iUs, iVs, iWs, iPs, iEs, &
                            & vUd, vVd, vWd, vPd, vEd, dUn, dVn, dWn, dPn, dEn, dUs, dVs, dWs, dPs, dEs, &
                            & cN, cL, cD, cAdiabatic)
							
				case (3) ! SSPRK3
					call SSPRK3_2D(U,V,W,R,E,Unew,Vnew,Rnew,Enew, &
                            & t, dt, Re, Ma, Pr, gamma, T0, &
                            & nDerivBlocksX,nDerivBlocksY,derivBlocksX,derivBlocksY, &
                            & derivnRHSx,derivnRHSy, &
                            & derivsAX, derivsBX, derivsCX, derivsRX, &
                            & derivsAY, derivsBY, derivsCY, derivsRY, &
                            & derivsDX, derivsDY, &
                            & periodicX, periodicY, &
                            & neumannLength, neumann2Length, neumannCoeffs, neumann2Coeffs, &
                            & nUd, nVd, nWd, nPd, nEd, nUn, nVn, nWn, nPn, nEn, nUs, nVs, nWs, nPs, nEs, &
                            & iUd, iVd, iWd, iPd, iEd, iUn, iVn, iWn, iPn, iEn, iUs, iVs, iWs, iPs, iEs, &
                            & vUd, vVd, vWd, vPd, vEd, dUn, dVn, dWn, dPn, dEn, dUs, dVs, dWs, dPs, dEs, &
                            & cN, cL, cD, cAdiabatic)
            end select
            
        else
            select case(timeStepping)
                case (1) ! RK4
                    call RK4_3D(U,V,W,R,E,Unew,Vnew,Wnew,Rnew,Enew, &
                            & t, dt, Re, Ma, Pr, gamma, T0, &
                            & nDerivBlocksX,nDerivBlocksY,nDerivBlocksZ,derivBlocksX,derivBlocksY,derivBlocksZ, &
                            & derivnRHSx,derivnRHSy,derivnRHSz, &
                            & derivsAX, derivsBX, derivsCX, derivsRX, &
                            & derivsAY, derivsBY, derivsCY, derivsRY, &
                            & derivsAZ, derivsBZ, derivsCZ, derivsRZ, &
                            & derivsDX, derivsDY, derivsDZ, &
                            & periodicX, periodicY, periodicZ, &
                            & neumannLength, neumann2Length, neumannCoeffs, neumann2Coeffs, &
                            & nUd, nVd, nWd, nPd, nEd, nUn, nVn, nWn, nPn, nEn, nUs, nVs, nWs, nPs, nEs, &
                            & iUd, iVd, iWd, iPd, iEd, iUn, iVn, iWn, iPn, iEn, iUs, iVs, iWs, iPs, iEs, &
                            & vUd, vVd, vWd, vPd, vEd, dUn, dVn, dWn, dPn, dEn, dUs, dVs, dWs, dPs, dEs, &
                            & cN, cL, cD, cAdiabatic)
                            
                case (2) ! EULER
                    call EULER_3D(U,V,W,R,E,Unew,Vnew,Wnew,Rnew,Enew, &
                            & t, dt, Re, Ma, Pr, gamma, T0, &
                            & nDerivBlocksX,nDerivBlocksY,nDerivBlocksZ,derivBlocksX,derivBlocksY,derivBlocksZ, &
                            & derivnRHSx,derivnRHSy,derivnRHSz, &
                            & derivsAX, derivsBX, derivsCX, derivsRX, &
                            & derivsAY, derivsBY, derivsCY, derivsRY, &
                            & derivsAZ, derivsBZ, derivsCZ, derivsRZ, &
                            & derivsDX, derivsDY, derivsDZ, &
                            & periodicX, periodicY, periodicZ, &
                            & neumannLength, neumann2Length, neumannCoeffs, neumann2Coeffs, &
                            & nUd, nVd, nWd, nPd, nEd, nUn, nVn, nWn, nPn, nEn, nUs, nVs, nWs, nPs, nEs, &
                            & iUd, iVd, iWd, iPd, iEd, iUn, iVn, iWn, iPn, iEn, iUs, iVs, iWs, iPs, iEs, &
                            & vUd, vVd, vWd, vPd, vEd, dUn, dVn, dWn, dPn, dEn, dUs, dVs, dWs, dPs, dEs, &
                            & cN, cL, cD, cAdiabatic)
							
							
                case (3) ! SSPRK3
                    call SSPRK3_3D(U,V,W,R,E,Unew,Vnew,Wnew,Rnew,Enew, &
                            & t, dt, Re, Ma, Pr, gamma, T0, &
                            & nDerivBlocksX,nDerivBlocksY,nDerivBlocksZ,derivBlocksX,derivBlocksY,derivBlocksZ, &
                            & derivnRHSx,derivnRHSy,derivnRHSz, &
                            & derivsAX, derivsBX, derivsCX, derivsRX, &
                            & derivsAY, derivsBY, derivsCY, derivsRY, &
                            & derivsAZ, derivsBZ, derivsCZ, derivsRZ, &
                            & derivsDX, derivsDY, derivsDZ, &
                            & periodicX, periodicY, periodicZ, &
                            & neumannLength, neumann2Length, neumannCoeffs, neumann2Coeffs, &
                            & nUd, nVd, nWd, nPd, nEd, nUn, nVn, nWn, nPn, nEn, nUs, nVs, nWs, nPs, nEs, &
                            & iUd, iVd, iWd, iPd, iEd, iUn, iVn, iWn, iPn, iEn, iUs, iVs, iWs, iPs, iEs, &
                            & vUd, vVd, vWd, vPd, vEd, dUn, dVn, dWn, dPn, dEn, dUs, dVs, dWs, dPs, dEs, &
                            & cN, cL, cD, cAdiabatic)
            end select
            
        endif
		
        ! Apply anti-aliasing filter
        if(nz.eq.1) then
            call applyFilters2D(Unew,Vnew,Rnew,Enew,FilterX,FilterY, &
                            & nDerivBlocksX,nDerivBlocksY,derivBlocksX,derivBlocksY, &
                            & filternRHSx,filternRHSy, &
                            & filterAX, filterBX, filterCX, filterRX, &
                            & filterAY, filterBY, filterCY, filterRY, &
                            & filterDX, filterDY, &
                            & periodicX, periodicY, &
							& dt/FilterCharTime)
                            
        else
            call applyFilters3D(Unew,Vnew,Wnew,Rnew,Enew,FilterX,FilterY,FilterZ, &
                            & nDerivBlocksX,nDerivBlocksY,nDerivBlocksZ,derivBlocksX,derivBlocksY,derivBlocksZ, &
                            & filternRHSx,filternRHSy,filternRHSz, &
                            & filterAX, filterBX, filterCX, filterRX, &
                            & filterAY, filterBY, filterCY, filterRY, &
                            & filterAZ, filterBZ, filterCZ, filterRZ, &
                            & filterDX, filterDY, filterDZ, &
                            & periodicX, periodicY, periodicZ, &
							& dt/FilterCharTime)
        endif
		
        ! Apply SFD
        if(SFD.gt.0) then
			if(SFD_Delta.gt.0) then
				Umean = Umean + dt/SFD_Delta*(Unew-Umean)
				Vmean = Vmean + dt/SFD_Delta*(Vnew-Vmean)
				Rmean = Rmean + dt/SFD_Delta*(Rnew-Rmean)
				Emean = Emean + dt/SFD_Delta*(Enew-Emean)
			endif
		
            Unew = Unew - dt*SFD_X*(Unew-Umean)
            Vnew = Vnew - dt*SFD_X*(Vnew-Vmean)
            Rnew = Rnew - dt*SFD_X*(Rnew-Rmean)
            Enew = Enew - dt*SFD_X*(Enew-Emean)

            if(nz.gt.1) then
				if(SFD_Delta.gt.0) then
					Wmean = Wmean + dt/SFD_Delta*(Wnew-Wmean)
				endif
				Wnew = Wnew - dt*SFD_X*(Wnew-Wmean)
            endif
        
        endif
		
		! Apply boundary conditions
        call applyBoundCond(Unew,Vnew,Wnew,Rnew,Enew,gamma,t + dt, &
				& neumannLength, neumann2Length, neumannCoeffs, neumann2Coeffs, &
				& nUd, nVd, nWd, nPd, nEd, nUn, nVn, nWn, nPn, nEn, nUs, nVs, nWs, nPs, nEs, &
				& iUd, iVd, iWd, iPd, iEd, iUn, iVn, iWn, iPn, iEn, iUs, iVs, iWs, iPs, iEs, &
				& vUd, vVd, vWd, vPd, vEd, dUn, dVn, dWn, dPn, dEn, dUs, dVs, dWs, dPs, dEs, &
				& cN, cL, cD, cAdiabatic)

        cpu_time = cpu_time + (MPI_Wtime() - t1)

        ! Evaluate stop-condition only once for while to optmize multi-node simulations...		
        if ((mod(tstep,logAll).eq.0).or.(stepsUntilSaving.eq.0)) then

            ! Get maximum value changes in the domain
            maxChangeL(1) = maxval(abs(Unew - U))
            maxChangeL(2) = maxval(abs(Vnew - V))
            maxChangeL(3) = maxval(abs(Wnew - W))
            maxChangeL(4) = maxval(abs(Rnew - R))
            maxChangeL(5) = maxval(abs(Enew - E))
            
            t1 = MPI_Wtime()
            call MPI_REDUCE(maxChangeL,maxChange,5,MPI_REAL8,MPI_MAX,0,MPI_COMM_WORLD,ierror)
            comm_time = comm_time + (MPI_Wtime() - t1)
            
            ! Update time
            tstep = tstep + 1
            t = t + dt
            
            ! Write to screen
            if(nrank.eq.0) then
                call date_and_time(values=dt_values)

                write(*,*) ''
                write(*,'(A9,I10,A13,EN14.6E1,A7,ES10.5E1,A8,F8.5)') 'Step = ', tstep, 'Time = ', t, 'dt = ', dt, 'CFL = ', CFL
                write(*,'(3(A13,ES10.4))') 'U change = ', maxChange(1), 'V change = ', maxChange(2), 'W change = ', maxChange(3)
                write(*,'(A13,ES10.4,A13,ES10.4,A9,I2.2,":",I2.2,":",I2.2)') 'R change = ', maxChange(4),  'E change = ', maxChange(5),  '  Now =  ', dt_values(5), dt_values(6), dt_values(7)

                ! Check if flow has diverged
                if((any(isnan(maxChange))).OR.(sum(maxChange).eq.0)) then
                    stopDNS = .TRUE.
                    write(*,*) 'Flow has diverged, stopping'
                endif
            endif
            
            t1 = MPI_Wtime()
            ! Stop code if flow has diverged and save results
            CALL MPI_BCAST(stopDNS, 1, MPI_LOGICAL, 0, MPI_COMM_WORLD, ierror)
            comm_time = comm_time + (MPI_Wtime() - t1)

            if(stopDNS) then
                nSave = -1
                ! include 'exportFlow.F90'

                t1 = MPI_Wtime()
                ! Collective export via mpi/hdf5 asynchronous I/O
                call writeFlow(nSave,t,U,V,W,R,E, insideWall, nx, ny, nz, NaN)
                io_time = io_time + (MPI_Wtime() - t1)

                call decomp_2d_finalize
                call MPI_FINALIZE(ierror)
                stop
            endif

        else
            ! Update time
            tstep = tstep + 1
            t = t + dt

            call date_and_time(values=dt_values)
            write(*,'(A7,I5,3X,A7,I3,4X,A6,I2.2,":",I2.2,":",I2.2)') 'Step = ', tstep, 'Rank = ', nrank, 'Now = ', dt_values(5), dt_values(6), dt_values(7)
        endif
		
		! Update flow
		U = Unew; V = Vnew; R = Rnew ; E = Enew
        if (nz.gt.1) then
            W = Wnew
        endif

        ! Write to log file
        if ((mod(tstep,logAll).eq.0).or.(stepsUntilSaving.eq.0)) then

            t1 = MPI_Wtime()
            include 'writeTrackedPoints3.F90'        
            track_time = track_time + (MPI_Wtime() - t1)

        endif
        
        if (stepsUntilSaving.eq.0) then
			! include 'exportFlow.F90'

            t1 = MPI_Wtime(); t2 = MPI_Wtime(); t3 = MPI_Wtime()
            ! Collective export via mpi/hdf5 asynchronous I/O
			call writeFlow(nSave,t,U,V,W,R,E, insideWall, nx, ny, nz, NaN)
            print *, 'Rank', nrank, ' -> writeFlow (disk):', (MPI_Wtime() - t3)

			if(SFD.gt.0) then
				if(SFD_Delta.gt.0) then
					!include 'exportMeanFlow.F90'

                    t3 = MPI_Wtime()
                    ! Collective export via mpi/hdf5 asynchronous I/O
                    call writeMeanFlow(Umean,Vmean,Wmean,Rmean,Emean, insideWall, nx, ny, nz, NaN)
                    print *, 'Rank', nrank, ' -> writeMeanFlow (disk):', (MPI_Wtime() - t3)
				endif
			endif
            io_time = io_time + (MPI_Wtime() - t1)
            exp_time = (MPI_Wtime() - t2)
			
            ! Dump and reset of times...
            total_time = MPI_Wtime() - total_time
            cpu_usage_time = ((get_cpu_time() - tc1) / total_time) * 100.0

            call MPI_REDUCE(total_time, max_total_time, 1, MPI_DOUBLE_PRECISION, MPI_MAX, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(total_time, min_total_time, 1, MPI_DOUBLE_PRECISION, MPI_MIN, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(total_time, sum_total_time, 1, MPI_DOUBLE_PRECISION, MPI_SUM, 0, MPI_COMM_WORLD, ierror)

            call MPI_REDUCE(cpu_usage_time, max_cpu_usage_time, 1, MPI_DOUBLE_PRECISION, MPI_MAX, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(cpu_usage_time, min_cpu_usage_time, 1, MPI_DOUBLE_PRECISION, MPI_MIN, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(cpu_usage_time, sum_cpu_usage_time, 1, MPI_DOUBLE_PRECISION, MPI_SUM, 0, MPI_COMM_WORLD, ierror)

            call MPI_REDUCE(cpu_time, max_cpu_time, 1, MPI_DOUBLE_PRECISION, MPI_MAX, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(cpu_time, min_cpu_time, 1, MPI_DOUBLE_PRECISION, MPI_MIN, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(cpu_time, sum_cpu_time, 1, MPI_DOUBLE_PRECISION, MPI_SUM, 0, MPI_COMM_WORLD, ierror)

            call MPI_REDUCE(comm_time, max_comm_time, 1, MPI_DOUBLE_PRECISION, MPI_MAX, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(comm_time, min_comm_time, 1, MPI_DOUBLE_PRECISION, MPI_MIN, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(comm_time, sum_comm_time, 1, MPI_DOUBLE_PRECISION, MPI_SUM, 0, MPI_COMM_WORLD, ierror)

            call MPI_REDUCE(io_time, max_io_time, 1, MPI_DOUBLE_PRECISION, MPI_MAX, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(io_time, min_io_time, 1, MPI_DOUBLE_PRECISION, MPI_MIN, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(io_time, sum_io_time, 1, MPI_DOUBLE_PRECISION, MPI_SUM, 0, MPI_COMM_WORLD, ierror)

            call MPI_REDUCE(imp_time, max_imp_time, 1, MPI_DOUBLE_PRECISION, MPI_MAX, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(imp_time, min_imp_time, 1, MPI_DOUBLE_PRECISION, MPI_MIN, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(imp_time, sum_imp_time, 1, MPI_DOUBLE_PRECISION, MPI_SUM, 0, MPI_COMM_WORLD, ierror)

            call MPI_REDUCE(exp_time, max_exp_time, 1, MPI_DOUBLE_PRECISION, MPI_MAX, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(exp_time, min_exp_time, 1, MPI_DOUBLE_PRECISION, MPI_MIN, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(exp_time, sum_exp_time, 1, MPI_DOUBLE_PRECISION, MPI_SUM, 0, MPI_COMM_WORLD, ierror)

            call MPI_REDUCE(track_time, max_track_time, 1, MPI_DOUBLE_PRECISION, MPI_MAX, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(track_time, min_track_time, 1, MPI_DOUBLE_PRECISION, MPI_MIN, 0, MPI_COMM_WORLD, ierror)
            call MPI_REDUCE(track_time, sum_track_time, 1, MPI_DOUBLE_PRECISION, MPI_SUM, 0, MPI_COMM_WORLD, ierror)

            if (nrank .eq. 0) then
                print *, 'Prof total (sum/max/min/avg):', sum_total_time, max_total_time, min_total_time, (sum_total_time/(p_col*p_row)) 
                print *, 'Prof %cpu  (sum/max/min/avg):', sum_cpu_usage_time, max_cpu_usage_time, min_cpu_usage_time, (sum_cpu_usage_time/(p_col*p_row)) 
                print *, 'Prof cpu   (sum/max/min/avg):', sum_cpu_time, max_cpu_time, min_cpu_time, (sum_cpu_time/(p_col*p_row)) 
                print *, 'Prof comm  (sum/max/min/avg):', sum_comm_time, max_comm_time, min_comm_time, (sum_comm_time/(p_col*p_row)) 
                print *, 'Prof io    (sum/max/min/avg):', sum_io_time, max_io_time, min_io_time, (sum_io_time/(p_col*p_row)) 
                print *, 'Prof imp   (sum/max/min/avg):', sum_imp_time, max_imp_time, min_imp_time, (sum_imp_time/(p_col*p_row)) 
                print *, 'Prof exp   (sum/max/min/avg):', sum_exp_time, max_exp_time, min_exp_time, (sum_exp_time/(p_col*p_row)) 
                print *, 'Prof track (sum/max/min/avg):', sum_track_time, max_track_time, min_track_time, (sum_track_time/(p_col*p_row)) 
            end if

            total_time = MPI_Wtime(); tc1 = get_cpu_time()
            cpu_time = 0.0d0; comm_time = 0.0d0; io_time = 0.0d0; exp_time = 0.0d0; track_time = 0.0d0

        endif
    
    end do
    
    ! Clean up
    call decomp_2d_finalize
    call MPI_FINALIZE(ierror)
    
    end program